### ISSUE TITLE
Generated nodes input variable in rke_cluster resource

### ISSUE THREAD

**Issue by gaui** [yamamoto-febc/terraform-provider-rke#5]
I'm having a problem, I have a Map with N keys/values for each cluster node. In the Map, the key is the node's hostname and value is the node's IP.

**Example:**

```
{
    "node1": "192.168.176.54",
    "node2": "192.168.176.55"
}
```

I'm trying to convert it into a ListMap to satisfy the `nodes` input variable in the `rke_cluster` resource.

**To something like this:**

```
[{
    address = "192.168.176.54"
    user    = "some static string"
    role    = ["controlplane", "etcd", "worker"]
    ssh_key = "my SSH key"
},
{
    address = "192.168.176.55"
    user    = "some static string"
    role    = ["controlplane", "etcd", "worker"]
    ssh_key = "my SSH key"
}]
```

**What I have is the following Terraform code:**

```
data "null_data_source" rke_nodes {
  count = "${length(keys(var.nodes))}"

  inputs = {
    address = "${element(values(var.nodes), count.index)}"
    user    = "${var.ssh_username}"
    role    = "controlplane,etcd,worker"
    ssh_key = "${file(var.ssh_private_key_path)}"
  }
}

resource "rke_cluster" rke_cluster {
  nodes = ["${data.null_data_source.rke_nodes.*.outputs}"]

  ingress = {
    provider = ""

    extra_args = {
      enable-ssl-passthrough = ""
    }
  }
}
```

**When I apply this, I get the following error from the `rke_cluster` resource:**

```
+ terraform apply
Releasing state lock. This may take a few moments...

Error: module.vsphere.module.rancher.module.rancher_cluster.module.rke.rke_cluster.rke_cluster: "nodes.0.address": required field is not set

Error: module.vsphere.module.rancher.module.rancher_cluster.module.rke.rke_cluster.rke_cluster: "nodes.0.role": required field is not set
```

**Output gives me:**

```
rancher_rke = [
    {
        address = 192.168.176.54,
        role = controlplane,etcd,worker,
        ssh_key = CENSORED,
        user = myuser
    },
    {
        address = 192.168.176.55,
        role = controlplane,etcd,worker,
        ssh_key = CENSORED,
        user = myuser
    }
]
```

On a side note, I'm also having problem specifying a list for `role` in `null_data_source` resource.

Can you guide me?

**Comment by yamamoto-febc** [comment]
Hi @gaui,

I think this strange behavior is because of a bug in Terraform core.
(ref: https://github.com/hashicorp/terraform/issues/15915)

This issue will probably resolved by support of dynamic block configuration on Terraform core (discussed in https://github.com/hashicorp/terraform/issues/7034).

**Comment by gaui** [comment]
@yamamoto-febc Until the dynamic block lands, can you think of some kind of a workaround?

**Comment by gaui** [comment]
@yamamoto-febc Thank you but I really don't want to introduce some kind of a template engine to achieve this.

As you can see in my output above with `null_data_source` looks correct (except the `role` comma separated string), but still it says `node.0.address` is not set. Why is that?

**Comment by gaui** [comment]
Could you make it optional to pass comma seperated values for the `role` variable? Then all variables would have the same type and would be easier to work with strings instead of arrays, because Terraform current state sucks regarding collections and looping.

Something like:

```
resource rke_cluster "cluster" {
  nodes = [
    {
      address = "1.2.3.4"
      user    = "rancher"
      role    = "controlplane,worker,etcd"
      ssh_key = "${file("~/.ssh/id_rsa")}"
    },
  ]
}
```

**Comment by sebastien-prudhomme** [comment]
Same problem on my side. I finally use a Terraform null_ressource to generate the cluster.yml file that the RKE binary can use.

Terraform still have a lot of limitations when you want to build complex structure. Perhaps adding an "rke_node" new resource type would be the solution:

```hcl
resource "rke_node" rke_nodes {
  count = "${length(keys(var.nodes))}"
  address = "${element(values(var.nodes), count.index)}"
  user    = "${var.ssh_username}"
  role    = "controlplane,etcd,worker"
  ssh_key = "${file(var.ssh_private_key_path)}"
}

resource "rke_cluster" rke_cluster {
  nodes = "${rke_node.rke_nodes.*}"

  ingress = {
    provider = ""

    extra_args = {
      enable-ssl-passthrough = ""
    }
  }
}
```

**Comment by gaui** [comment]
Yes, `rke_node` would make perfect sense. It then would be aggregated to a collection of nodes. This would solve our problem.

**Comment by yamamoto-febc** [comment]
I'm sorry for late response.

>As you can see in my output above with null_data_source looks correct (except the role comma separated string), but still it says node.0.address is not set. Why is that?

It is not possible to dynamically produce child blocks in this way. 
That is limitation of current version of terraform.

---

> Could you make it optional to pass comma seperated values for the role variable? ...

It is recommended to pass the role as a list as follows:

```
 role = ["${split(",", var.role)}"]
```

Is this useless? What kind of use case would you like to use comma separated strings?

Note: `node` has attributes of map type such as `labels` besides `role`, it is difficult to make all attributes as strings.

---

> Perhaps adding an "rke_node" new resource type would be the solution

It is one way to solve it, but I do not want to implement it now.

In the near future, I think that it can solve by dynamic block(HCL2). 
This makes it easier to keep the provider implementation simple.

However, if Terraform v0.12 is not released in the near future, I will consider adding the rke_node resource type.
(But PR is always welcome!)

**Comment by sebastien-prudhomme** [comment]
@yamamoto-febc Do you now if HCL2 will allow to build dynamic structures like that:

```hcl
role = "${count.index < var.count_master ? jsonencode(list("controlplane", "etcd", "worker")) : jsonencode(list("worker"))}"
```

**Comment by yamamoto-febc** [comment]
@sebastien-prudhomme 

I'm sorry, I could not understand what you wrote...

Why are you using `jsonencode`?

`role` is defined as `schema.TypeList`(not a string), 
so if you want to dynamically change the `role` with the value of count.index, you can do as follows:

```tf
role = "${count.index < var.count_master ? list("controlplane", "etcd", "worker") : list("worker")}"
```

**Comment by sebastien-prudhomme** [comment]
Sorry, i just copied what i'm using to generate the template file i use for launching RKE binary. No need for jsonencode for rke_cluster ressource.

**Comment by gaui** [comment]
@yamamoto-febc 

Thank you for your response. Is there some release date or a milestone for HCL2/0.12 we can track? Not sure if it's close or not, but this is a major blocker for us.

The `role` is a list yes, but the only native TF solution I've found so far was to use `null_data_source` but it doesn't support lists - which is problematic.

**Comment by gaui** [comment]
@yamamoto-febc

Is it a major change if you add a new variable that accepts roles as a string (comma seperated values)? Until HCL2 / TF 0.12 is released.

**Comment by gaui** [comment]
@yamamoto-febc You are a real lifesaver. Send me your PayPal in DM and I'll buy you a beer!

**Comment by gaui** [comment]
I tried this, `roles` works really well, but I still get...

```
Error: module.vsphere.module.rancher.module.rancher_cluster.module.rke.rke_cluster.rke_cluster: "nodes.0.address": required field is not set
```

I tried running `terraform output` with the data passed to `nodes` attr, wrapped around in `jsonencode()` and it outputs just fine. I am out of solutions.

**Comment by gaui** [comment]
@yamamoto-febc This is still an issue and I don't see any solution. This is a major blocker. Would it be possible to pass each information as a list into the resource, and specify some kind of `legacy_mode` switch?

Something like:

```
resource "rke_cluster" cluster {
  legacy_mode = "true"
  node_addresses = ["node1_ip", "node2_ip", "node3_ip"]
  node_roles = ["controlplane,etcd", ""controlplane,etcd,worker", "etcd,worker"]
  node_users = ["node1_user", "node2_user", "node3_user"]
  node_ssh_keys = ["node1_sshkey", "node2_sshkey", "node3_sshkey"]

  ingress = {
    provider = "nginx"
  }
}
```

**Comment by yamamoto-febc** [comment]
@gaui Thanks for the suggestion.  

But I don't like this way 😢💦

I think that adding the `node_xxx` attrs will make it more less usability.
Also, I'm concerned that the validation of added attributes will be complicated.

So, I came up with a way to specify `nodes` as JSON strings like follows:

```hcl
######################################################### 
# !! NOT YET IMPLEMENTED and may change before release
######################################################### 

variable node_addresses {
  type = "list"
  default = ["192.2.0.1", "192.2.0.2"]
}

# node(JSON)
data template_file "node_json" {
  count = "${length(var.node_addresses)}"
  template = <<EOF
    {
      "address": "$${address}",
      "user"   : "$${user}",
      "role"   : ["controlplane", "etcd", "worker"],
      "sshKey" : "$${ssh_key}"
    }
EOF

  vars {
    address = "${var.node_addresses[count.index]}"
    user    = "ubuntu"
    ssh_key = "${file("~/.ssh/id_rsa")}"
  }
}

// node-list JSON
locals {
  nodes_json = "[${join(",", data.template_file.node_json.*.rendered)}]"
}

resource rke_cluster "foobar" {
  nodes_json = "${local.nodes_json}" # nodes from JSON
}
```

How do you think about this?

**Comment by gaui** [comment]
I like it!

**Comment by gaui** [comment]
It would solve our problem. I did the exact same thing when generating the RKE YAML before I stumbled upon this provider. It would mean the world if this would be implemented. 🏆

**Comment by yamamoto-febc** [comment]
@gaui I came up with a better way to configure dynamic multiple nodes.

- Add the data source `rke_node_parameter` and output `JSON` or `YAML` from it.
- Add `nodes_conf` attr to `rke_cluster` so that `JSON` or `YAML` strings can be accepted.

I have created a PR (#8) to do these.

**Comment by gaui** [comment]
@yamamoto-febc Awesome, looks really good! Thank you so much!
